services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis_gymbot
    ports:
      - "6379:6379"
    volumes:
      - /your_directory/redis_gymbot:/data
    restart: no

  mysql:
    image: mysql:8.0.41-bookworm
    container_name: mysql_gymbot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /your_directory/mysql_gymbot:/var/lib/mysql
    restart: no

  bot:
    image: danil20/bot_gym:latest
    container_name: bot_gym_container
    depends_on:
      - redis
      - mysql
    environment:
      BOT_TOKEN: "your_token"
      TYPE_DB: "mysql"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      HOST_DB: "mysql"
      PORT_DB: "3306"
      USER_DB: "root"
      PASSWORD_DB: "root"
      NAME_DB: "gymbot"
    restart: no

volumes:
  redis_data:
  mysql_data: